# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-19 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltApp', '0002_auto_20190718_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creates', to='beltApp.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='wish',
            name='like',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='wisher',
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
