# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-22 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltApp', '0003_auto_20190719_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='add',
            field=models.ManyToManyField(related_name='adds', to='beltApp.User'),
        ),
    ]
