# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-22 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltApp', '0004_job_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='add',
            field=models.ManyToManyField(related_name='jobs', to='beltApp.User'),
        ),
    ]
